name: ruff_wallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.10+1
  bip32: ^1.0.5
  bip39: ^1.0.3
  shared_preferences: ^0.5.3
  http: ^0.12.0+2
  barcode_scan: ^1.0.0
  qr_flutter: ^2.1.0+55
  date_format: ^1.0.6
  url_launcher: ^5.2.1
  flutter_inappbrowser: ^1.2.1
  package_info: ^0.4.0
  pub_semver: ^1.4.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  intl_translation: "^0.17.3"

# https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/js-lib/
    - assets/images/
